### ISSUE TITLE
RealignmentProcessor can visit negative genome coordinates

### ISSUE THREAD

**Issue by fac2003** [CampagneLaboratory/goby#2]
Got this exception on a genotyping run with Goby 2.1.3-pre-release.
java.lang.IndexOutOfBoundsException: Index (-1) is negative
        at it.unimi.dsi.bits.AbstractBitVector.ensureRestrictedIndex(AbstractBitVector.java:58)
        at it.unimi.dsi.bits.LongArrayBitVector.getBoolean(LongArrayBitVector.java:366)
        at it.unimi.dsi.bits.AbstractBitVector.getBoolean(AbstractBitVector.java:90)
        at it.unimi.dsi.fastutil.booleans.AbstractBooleanList.get(AbstractBooleanList.java:391)
        at edu.cornell.med.icb.goby.reads.RandomAccessSequenceCache.get(RandomAccessSequenceCache.java:351)
        at edu.cornell.med.icb.goby.alignments.processors.RealignmentProcessor.realign(RealignmentProcessor.java:328)
        at edu.cornell.med.icb.goby.alignments.processors.RealignmentProcessor.realign(RealignmentProcessor.java:223)
        at edu.cornell.med.icb.goby.alignments.processors.RealignmentProcessor.nextRealignedEntry(RealignmentProcessor.java:165)
        at edu.cornell.med.icb.goby.alignments.processors.LocalSortProcessor.nextRealignedEntry(LocalSortProcessor.java:106)
        at edu.cornell.med.icb.goby.alignments.IterateSortedAlignments.iterate(IterateSortedAlignments.java:327)
        at edu.cornell.med.icb.goby.modes.DiscoverSequenceVariantsMode.execute(DiscoverSequenceVariantsMode.java:727)
        at edu.cornell.med.icb.goby.modes.GenericToolsDriver.execute(GenericToolsDriver.java:219)
        at edu.cornell.med.icb.goby.modes.GobyDriver.main(GobyDriver.java:55)

**Comment by fac2003** [comment]
Should be resolved in upcoming 2.2 release.

**Comment by fac2003** [comment]
This was resolved in version 2.2.
