### ISSUE TITLE
NPE when running discovery-sequence-variants with no groups. 

### ISSUE THREAD

**Issue by fac2003** [CampagneLaboratory/goby#3]
The following NPE can be observed when running discovery-sequence-variants with no groups. 

java.lang.NullPointerException
    at edu.cornell.med.icb.goby.modes.DiscoverSequenceVariantsMode.configure(DiscoverSequenceVariantsMode.java:192)
    at edu.cornell.med.icb.goby.modes.GenericToolsDriver.execute(GenericToolsDriver.java:218)
    at edu.cornell.med.icb.goby.modes.GobyDriver.main(GobyDriver.java:55)

**Comment by fac2003** [comment]
A simple work-around consist in adding a group that contains at least one sample, for instance:
--groups sample=some-sample, where some-sample must match the basename of one of the alignments provided on the command line.

**Comment by fac2003** [comment]
This bug is fixed in GitHub stable branch. Will be part of the next stable release.

**Comment by fac2003** [comment]
Fixed in 2.3.1.
